version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - plum-network

  backend:
    image: plum-classification-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./media:/app/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,backend
      - CORS_ALLOWED_ORIGINS=http://localhost,http://frontend
    networks:
      - plum-network

networks:
  plum-network:
    driver: bridge
