version: '3'

services:
  plum-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:8000/api/
    restart: unless-stopped
